package entity;
// Generated Feb 13, 2020, 1:16:39 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Registration generated by hbm2java
 */
@Entity (name = "registration")
@Table(name = "registration", catalog = "jwat")
public class Registration implements java.io.Serializable {

	private String idUser;
	private Users users;
	private Boolean morning2;
	private Boolean afternoon2;
	private Boolean morning3;
	private Boolean afternoon3;
	private Boolean morning4;
	private Boolean afternoon4;
	private Boolean morning5;
	private Boolean afternoon5;
	private Boolean morning6;
	private Boolean afternoon6;
	private Boolean morning7;
	private Boolean afternoon7;
	private Boolean morning8;
	private Boolean afternoon8;
	private Boolean isRegister;

	public Registration() {
	}

	public Registration(Users users) {
		this.users = users;
	}

	public Registration(Users users, Boolean morning2, Boolean afternoon2, Boolean morning3, Boolean afternoon3,
			Boolean morning4, Boolean afternoon4, Boolean morning5, Boolean afternoon5, Boolean morning6,
			Boolean afternoon6, Boolean morning7, Boolean afternoon7, Boolean morning8, Boolean afternoon8,
			Boolean isRegister) {
		this.users = users;
		this.morning2 = morning2;
		this.afternoon2 = afternoon2;
		this.morning3 = morning3;
		this.afternoon3 = afternoon3;
		this.morning4 = morning4;
		this.afternoon4 = afternoon4;
		this.morning5 = morning5;
		this.afternoon5 = afternoon5;
		this.morning6 = morning6;
		this.afternoon6 = afternoon6;
		this.morning7 = morning7;
		this.afternoon7 = afternoon7;
		this.morning8 = morning8;
		this.afternoon8 = afternoon8;
		this.isRegister = isRegister;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "users"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id_user", unique = true, nullable = false, length = 100)
	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "morning2")
	public Boolean getMorning2() {
		return this.morning2;
	}

	public void setMorning2(Boolean morning2) {
		this.morning2 = morning2;
	}

	@Column(name = "afternoon2")
	public Boolean getAfternoon2() {
		return this.afternoon2;
	}

	public void setAfternoon2(Boolean afternoon2) {
		this.afternoon2 = afternoon2;
	}

	@Column(name = "morning3")
	public Boolean getMorning3() {
		return this.morning3;
	}

	public void setMorning3(Boolean morning3) {
		this.morning3 = morning3;
	}

	@Column(name = "afternoon3")
	public Boolean getAfternoon3() {
		return this.afternoon3;
	}

	public void setAfternoon3(Boolean afternoon3) {
		this.afternoon3 = afternoon3;
	}

	@Column(name = "morning4")
	public Boolean getMorning4() {
		return this.morning4;
	}

	public void setMorning4(Boolean morning4) {
		this.morning4 = morning4;
	}

	@Column(name = "afternoon4")
	public Boolean getAfternoon4() {
		return this.afternoon4;
	}

	public void setAfternoon4(Boolean afternoon4) {
		this.afternoon4 = afternoon4;
	}

	@Column(name = "morning5")
	public Boolean getMorning5() {
		return this.morning5;
	}

	public void setMorning5(Boolean morning5) {
		this.morning5 = morning5;
	}

	@Column(name = "afternoon5")
	public Boolean getAfternoon5() {
		return this.afternoon5;
	}

	public void setAfternoon5(Boolean afternoon5) {
		this.afternoon5 = afternoon5;
	}

	@Column(name = "morning6")
	public Boolean getMorning6() {
		return this.morning6;
	}

	public void setMorning6(Boolean morning6) {
		this.morning6 = morning6;
	}

	@Column(name = "afternoon6")
	public Boolean getAfternoon6() {
		return this.afternoon6;
	}

	public void setAfternoon6(Boolean afternoon6) {
		this.afternoon6 = afternoon6;
	}

	@Column(name = "morning7")
	public Boolean getMorning7() {
		return this.morning7;
	}

	public void setMorning7(Boolean morning7) {
		this.morning7 = morning7;
	}

	@Column(name = "afternoon7")
	public Boolean getAfternoon7() {
		return this.afternoon7;
	}

	public void setAfternoon7(Boolean afternoon7) {
		this.afternoon7 = afternoon7;
	}

	@Column(name = "morning8")
	public Boolean getMorning8() {
		return this.morning8;
	}

	public void setMorning8(Boolean morning8) {
		this.morning8 = morning8;
	}

	@Column(name = "afternoon8")
	public Boolean getAfternoon8() {
		return this.afternoon8;
	}

	public void setAfternoon8(Boolean afternoon8) {
		this.afternoon8 = afternoon8;
	}

	@Column(name = "isRegister")
	public Boolean getIsRegister() {
		return this.isRegister;
	}

	public void setIsRegister(Boolean isRegister) {
		this.isRegister = isRegister;
	}

}
