package entity;
// Generated Feb 13, 2020, 1:16:39 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule", catalog = "jwat")
public class Schedule implements java.io.Serializable {

	private String idTuanvaBuoi;
	private String idTuan;
	private String idBuoi;
	private String noiDung;
	private String phong;
	private Integer soLuong;
	private String ghiChu;

	public Schedule() {
	}

	public Schedule(String idTuanvaBuoi) {
		this.idTuanvaBuoi = idTuanvaBuoi;
	}

	public Schedule(String idTuanvaBuoi, String idTuan, String idBuoi, String noiDung, String phong, Integer soLuong,
			String ghiChu) {
		this.idTuanvaBuoi = idTuanvaBuoi;
		this.idTuan = idTuan;
		this.idBuoi = idBuoi;
		this.noiDung = noiDung;
		this.phong = phong;
		this.soLuong = soLuong;
		this.ghiChu = ghiChu;
	}

	@Id

	@Column(name = "idTuanvaBuoi", unique = true, nullable = false, length = 100)
	public String getIdTuanvaBuoi() {
		return this.idTuanvaBuoi;
	}

	public void setIdTuanvaBuoi(String idTuanvaBuoi) {
		this.idTuanvaBuoi = idTuanvaBuoi;
	}

	@Column(name = "idTuan", length = 100)
	public String getIdTuan() {
		return this.idTuan;
	}

	public void setIdTuan(String idTuan) {
		this.idTuan = idTuan;
	}

	@Column(name = "idBuoi", length = 100)
	public String getIdBuoi() {
		return this.idBuoi;
	}

	public void setIdBuoi(String idBuoi) {
		this.idBuoi = idBuoi;
	}

	@Column(name = "NoiDung", length = 100)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@Column(name = "phong", length = 100)
	public String getPhong() {
		return this.phong;
	}

	public void setPhong(String phong) {
		this.phong = phong;
	}

	@Column(name = "soLuong")
	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "ghiChu", length = 100)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

}
